#@TYPE: Machine
#@NAME: RaspberryPi 3 Development Board
#@DESCRIPTION: Machine configuration for the RaspberryPi 3 in 64 bits mode

MACHINEOVERRIDES =. "raspberrypi3:"

require conf/machine/raspberrypi3-64.conf
require conf/machine/include/security_flags.inc
require conf/machine/include/no-gplv3.inc

SERIAL_CONSOLES ?= "115200;ttyS0"

# Bootloader
UBOOT_MACHINE = "rpi_arm64_config"
PREFERRED_PROVIDER_virtual/bootloader = "u-boot"
RPI_USE_U_BOOT = "1"

MACHINE_FEATURES = "\
    apm \
    usbhost \
    keyboard \
    vfat \
    ext2 \
    screen \
    bluetooth \
    wifi \
    sdio \
    ${@bb.utils.contains('DISABLE_VC4GRAPHICS', '1', '', 'vc4graphics', d)}\
"
