# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-omar"
BBFILE_PATTERN_meta-omar = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-omar = "6"

LAYERDEPENDS_meta-omar = "core"
LAYERSERIES_COMPAT_meta-omar = "scarthgap"
