# [system]
compatible=YoctoProject-RPi3
bootloader=uboot
# bundle-formats=-plain
# 
# [slot.rootfs.0]
# device=/dev/mmcblkXp1
# type=ext4
# bootname=system0
# 
# [slot.rootfs.1]
# device=/dev/mmcblkXp2
# type=ext4
# bootname=system1
#
# [slot.appfs.0]
# device=/dev/mmcblkXp3
# type=ext4
# parent=rootfs.0
#
# [slot.appfs.1]
# device=/dev/mmcblkXp4
# type=ext4
# parent=rootfs.1
