#[system]
#compatible=raspberrypi3
#bootloader=u-boot

#[keyring]
#path=/etc/rauc/keyring.pem

#[slot.rootfs.0]
#device=/dev/mmcblk0p2
#type=ext4
#bootid=rootfsA

#[slot.rootfs.1]
#device=/dev/mmcblk0p3
#type=ext4
#bootid=rootfsB
